name: TranferPro
main: net.easecation.transferpro.TransferPro
version: 1.0.0
api:
  - 1.0.0
load: POSTWORLD
author: EaseCationTeam
permissions:
  tarnsferpro.transfer:
    default: true
    description: "Transfer"
  tarnsferpro.transferplayer:
    default: op
    description: "Transfer Player"
  tarnsferpro.tspro:
    default: op
    description: "Transfer Pro Manage"
depends:
  - "DbLib"